### ISSUE TITLE
ImportError: No module named '_testcapi'

### ISSUE THREAD

**Issue by AngusWG** [vollib/py_vollib#11]
using python from centos 7   ,
install python by ` yum install -y python35u ` . 

get error :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/py_vollib/black_scholes/__init__.py", line 44, in <module>
    from py_vollib.black import undiscounted_black
  File "/usr/lib/python3.5/site-packages/py_vollib/black/__init__.py", line 44, in <module>
    import py_lets_be_rational as lets_be_rational
  File "/usr/lib/python3.5/site-packages/py_lets_be_rational/__init__.py", line 30, in <module>
    from py_lets_be_rational.lets_be_rational import black
  File "/usr/lib/python3.5/site-packages/py_lets_be_rational/lets_be_rational.py", line 35, in <module>
    from py_lets_be_rational.exceptions import BelowIntrinsicException, AboveMaximumException
  File "/usr/lib/python3.5/site-packages/py_lets_be_rational/exceptions.py", line 30, in <module>
    from py_lets_be_rational import constants
  File "/usr/lib/python3.5/site-packages/py_lets_be_rational/constants.py", line 32, in <module>
    from _testcapi import DBL_MIN, DBL_MAX
ImportError: No module named '_testcapi'

[It should not be included in a production library](https://github.com/vollib/py_vollib/issues/1)

In an uncompiled version, this file does not necessarily exist .
please fix this problem

**Comment by jenish99** [comment]
Is this problem solved?

**Comment by yangibal** [comment]
I have the same issue now on Windows 10, 64. Tried installing pytest (via pip) as there was some hints on stackoverflow that this might help but it did not.

I get this when just trying to run implied_volatility.py directly:

looks like it's from a py_lets_be_rational import

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\yangi\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\yangi\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\yangi\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\yangi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\py_vollib\black_scholes\implied_volatility.py", line 40, in <module>
    from py_lets_be_rational import implied_volatility_from_a_transformed_rational_guess as iv
  File "C:\Users\yangi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\py_lets_be_rational\__init__.py", line 30, in <module>
    from py_lets_be_rational.lets_be_rational import black
  File "C:\Users\yangi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\py_lets_be_rational\lets_be_rational.py", line 35, in <module>
    from py_lets_be_rational.exceptions import BelowIntrinsicException, AboveMaximumException
  File "C:\Users\yangi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\py_lets_be_rational\exceptions.py", line 30, in <module>
    from py_lets_be_rational import constants
  File "C:\Users\yangi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\py_lets_be_rational\constants.py", 
line 32, in <module>
    from _testcapi import DBL_MIN, DBL_MAX
ModuleNotFoundError: No module named '_testcapi'

**Comment by yangibal** [comment]
replacing `from __testcapi import DBL_MAX, DBL_MIN` in constants.py in py_lets_be_rational.constants.py by `sys.float_info.min/max` solves the issue entirely

**Comment by lbrichards** [comment]
This is now fixed in the github repository.

**Comment by lbrichards** [comment]
Follow-up: the official `vollib 1.0.7` release is now published on PyPI and uses the repaired `py_lets_be_rational` dependency path.

Please install the official package going forward:

```bash
pip install -U vollib
```

The temporary `vollib-test` package is superseded by the official release.
