### ISSUE TITLE
Importing library in PyCharm Python Console raises ModuleNotFoundError

### ISSUE THREAD

**Issue by guruappa** [vollib/py_vollib#20]
Hi guys,

I was trying the library out in the PyCharm IDE.  Whenever I try to import libraries, it is throwing the ModuleNotFoundError for _testcapi.  I did read in one of the closed issues that this is no longer an issue.  But I could not find a working solution to the issue on my computer.  I tried reinstalling the library multiple times.  Any help would be much appreciated.

I am trying the library on Python 3.10 on Fedora box.

>>> from py_vollib import black_scholes
Traceback (most recent call last):
  File "/usr/lib64/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/guruappa/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/run/media/guruappa/programs/projects/trade_station/venv/lib/python3.10/site-packages/py_vollib/black_scholes/__init__.py", line 44, in <module>
    from py_vollib.black import undiscounted_black
  File "/home/guruappa/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/run/media/guruappa/programs/projects/trade_station/venv/lib/python3.10/site-packages/py_vollib/black/__init__.py", line 44, in <module>
    import py_lets_be_rational as lets_be_rational
  File "/home/guruappa/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/run/media/guruappa/programs/projects/trade_station/venv/lib/python3.10/site-packages/py_lets_be_rational/__init__.py", line 30, in <module>
    from py_lets_be_rational.lets_be_rational import black
  File "/home/guruappa/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/run/media/guruappa/programs/projects/trade_station/venv/lib/python3.10/site-packages/py_lets_be_rational/lets_be_rational.py", line 35, in <module>
    from py_lets_be_rational.exceptions import BelowIntrinsicException, AboveMaximumException
  File "/home/guruappa/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/run/media/guruappa/programs/projects/trade_station/venv/lib/python3.10/site-packages/py_lets_be_rational/exceptions.py", line 30, in <module>
    from py_lets_be_rational import constants
  File "/home/guruappa/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/run/media/guruappa/programs/projects/trade_station/venv/lib/python3.10/site-packages/py_lets_be_rational/constants.py", line 32, in <module>
    from _testcapi import DBL_MIN, DBL_MAX
  File "/home/guruappa/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named '_testcapi'

**Comment by lbrichards** [comment]
fixed in github repository (not yet in PyPI)

**Comment by lbrichards** [comment]
Follow-up: the official `vollib 1.0.7` release is now published on PyPI and uses the repaired `py_lets_be_rational` dependency path.

Please install the official package going forward:

```bash
pip install -U vollib
```

The temporary `vollib-test` package is superseded by the official release.
